# Generated by Django 2.1.3 on 2019-08-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190628_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearCharts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=6)),
                ('grant_total', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
