# Generated by Django 2.1.3 on 2019-06-19 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_partner_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_Cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ProductCategory'),
            preserve_default=False,
        ),
    ]
