# Generated by Django 2.1.3 on 2019-05-15 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_accountdefault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdefault',
            name='CustomerAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerAcnt', to='core.Account'),
        ),
        migrations.AlterField(
            model_name='accountdefault',
            name='PurchaseAccont',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseAcnt', to='core.Account'),
        ),
        migrations.AlterField(
            model_name='accountdefault',
            name='SalesAccont',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SalesAcnt', to='core.Account'),
        ),
        migrations.AlterField(
            model_name='accountdefault',
            name='SupplierAccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SupplierAcnt', to='core.Account'),
        ),
    ]
