# Generated by Django 2.2.4 on 2019-09-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_expenseyearchart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceLine',
            new_name='InvoiceLineOld',
        ),
    ]
