# Generated by Django 2.1.3 on 2019-05-18 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190515_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept_no', models.IntegerField()),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.JournalEntry')),
            ],
        ),
    ]
