# Generated by Django 2.1.3 on 2019-05-22 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190520_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalitem',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.JournalEntry'),
        ),
    ]
