# Generated by Django 2.2.4 on 2019-09-18 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_salesinvoicenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoicenu',
            name='child',
        ),
        migrations.AddField(
            model_name='salesinvoicenu',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.InvoiceLine'),
        ),
    ]
