# Generated by Django 2.1.3 on 2019-05-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_journalitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(blank=True, choices=[('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('DEBITNOTE', 'DebitNote'), ('CREDITNOTE', 'CreditNote'), ('COSTOMER_RECIEPT', 'CustomerReceipt'), ('SUPPLIER_PAYMENT', 'SupplierPayment'), ('EXPENSE', 'Expense'), ('JOURNAL', 'Journal')], default='SALES', max_length=15, null=True)),
                ('description', models.CharField(blank=True, max_length=15, null=True)),
                ('journal_item', models.ManyToManyField(to='core.JournalItems')),
            ],
        ),
    ]
