# Generated by Django 2.2.4 on 2019-09-18 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190918_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoicenu',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Branch'),
        ),
    ]
