# Generated by Django 2.1.3 on 2019-05-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_journalentries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentries',
            old_name='journal_item',
            new_name='journal_items',
        ),
    ]
