# Generated by Django 2.1.3 on 2019-05-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190529_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReceipts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept_no', models.IntegerField()),
            ],
        ),
    ]
