# Generated by Django 2.1.3 on 2019-05-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customerreceipts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('DEBITNOTE', 'DebitNote'), ('CREDITNOTE', 'CreditNote'), ('COSTOMER_RECIEPT', 'CustomerReceipt'), ('SUPPLIER_PAYMENT', 'SupplierPayment'), ('EXPENSE', 'Expense'), ('JOURNAL', 'Journal')], default='SALES', max_length=100, null=True),
        ),
    ]
