# Generated by Django 2.2.4 on 2019-09-19 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190918_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doc_no', models.IntegerField()),
                ('Grand_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Date', models.DateField()),
                ('Comment', models.CharField(blank=True, max_length=500, null=True)),
                ('Partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Partner')),
            ],
        ),
    ]
