# Generated by Django 2.2.4 on 2019-09-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_creditnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNoteNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=6)),
                ('suffix', models.CharField(max_length=6)),
                ('start_number', models.IntegerField()),
            ],
        ),
    ]
