# Generated by Django 2.1.3 on 2019-06-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190531_1209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerReceipts',
        ),
        migrations.RemoveField(
            model_name='journalentries',
            name='journal_items',
        ),
        migrations.RemoveField(
            model_name='journalitems',
            name='account',
        ),
        migrations.RemoveField(
            model_name='journalitems',
            name='partner',
        ),
        migrations.DeleteModel(
            name='JournalEntries',
        ),
        migrations.DeleteModel(
            name='JournalItems',
        ),
    ]
