# Generated by Django 2.2.4 on 2019-09-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_creditnotenumber_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnotenumber',
            name='start_number',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
