# Generated by Django 2.2.4 on 2019-09-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190919_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnotenumber',
            name='start_number',
            field=models.IntegerField(),
        ),
    ]
