# Generated by Django 2.1.3 on 2019-06-12 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_expenses_journal_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c_invoice',
            name='key',
        ),
        migrations.RemoveField(
            model_name='p_invoice',
            name='journal_entry',
        ),
        migrations.DeleteModel(
            name='C_Invoice',
        ),
        migrations.DeleteModel(
            name='P_Invoice',
        ),
    ]
