# Generated by Django 2.1.3 on 2019-06-12 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20190612_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField()),
                ('doc_no', models.IntegerField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('narration', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('grant_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ChildInvoice')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.JournalEntry')),
            ],
        ),
    ]
