# Generated by Django 2.1.3 on 2019-06-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_parentinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=60)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.RenameModel(
            old_name='ParentInvoice',
            new_name='SalesInvoice',
        ),
    ]
