# Generated by Django 2.1.3 on 2019-06-12 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190612_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.InvoiceLine'),
        ),
    ]
