# Generated by Django 2.1.3 on 2019-06-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20190612_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='child',
            new_name='invoice_line',
        ),
    ]
