# Generated by Django 2.1.3 on 2019-06-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190612_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='invoice_line',
            new_name='child',
        ),
    ]
