# Generated by Django 2.1.3 on 2019-06-18 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='edited_by',
            field=models.ManyToManyField(related_name='edited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
