# Generated by Django 2.1.3 on 2019-06-18 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_partner_edited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='edited_by',
        ),
        migrations.AddField(
            model_name='partner',
            name='edited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='edited_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
