# Generated by Django 2.2.4 on 2019-09-23 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Masters', '0001_initial'),
        ('Journal_Entry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNoteNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=6)),
                ('suffix', models.CharField(max_length=6)),
                ('start_number', models.IntegerField()),
                ('digits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doc_no', models.CharField(max_length=30)),
                ('Grand_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Date', models.DateField()),
                ('Comment', models.CharField(blank=True, max_length=500, null=True)),
                ('Partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.Partner')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Journal_Entry.JournalEntry')),
            ],
        ),
    ]
