# Generated by Django 2.2.4 on 2019-09-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Credit_Note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditnotenumber',
            old_name='digits',
            new_name='padding',
        ),
    ]
