# Generated by Django 2.2.4 on 2019-09-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Credit_Note', '0002_auto_20190924_1109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditNoteNumber',
        ),
    ]
