# Generated by Django 2.2.4 on 2019-09-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=6)),
                ('suffix', models.CharField(max_length=6)),
                ('start_number', models.IntegerField()),
                ('padding', models.IntegerField()),
                ('type', models.CharField(choices=[('CN', 'CreditNote'), ('DN', 'DebitNote'), ('SI', 'Sales'), ('CR', 'customer_reciept')], max_length=10)),
            ],
        ),
    ]
