# Generated by Django 2.2.4 on 2019-09-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_serialnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialnumber',
            name='type',
            field=models.CharField(choices=[('CN', 'CreditNote'), ('DN', 'DebitNote'), ('SI', 'Sales'), ('CR', 'customer_reciept'), ('EP', 'expense')], max_length=10),
        ),
    ]
