# Generated by Django 2.2.4 on 2019-09-22 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Journal_Entry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept_no', models.IntegerField()),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Journal_Entry.JournalEntry')),
            ],
        ),
    ]
