# Generated by Django 2.2.4 on 2019-09-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_Receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreceipt',
            name='reciept_no',
            field=models.CharField(max_length=60),
        ),
    ]
