# Generated by Django 2.2.4 on 2019-09-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Debit_Note', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DebitNoteNumber',
        ),
    ]
