# Generated by Django 2.2.4 on 2019-09-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_no',
            field=models.CharField(max_length=60),
        ),
    ]
